name: Deploy Java App to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/First-project
            git pull origin main
            chmod +x mvnw
            ./mvnw clean package
            sudo docker stop java-devops-demo || true
            sudo docker rm java-devops-demo || true
            sudo docker build -f dockerfile -t java-devops-demo .
            sudo docker run -d --name java-devops-demo -p 9090:9090 java-devops-demo
            sudo docker ps
